const vendor = [
  'babel-polyfill',
  'react',
  'react-dom',
  'react-redux',
  'react-proxy',
  'react-router',
  'react-router-redux',
  'react-virtualized',
  'redux',
  'redux-observable',
  'react-toolbox',
  'react-hot-loader',
  'rxjs',
  'lodash',
  'moment',
  'localforage',
  'react-loadable',
  'global',
  'react-hot-loader/patch',
  'create-react-class',
  'react-loader',
];
module.exports = vendor;
